#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o pipefail

# Configuration Parameters
OS_VERSION="7.3.1611"
KERNEL_VERSION="3.10.0-514.6.1.el7"

mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros

# Install required packages
sudo yum install -y gtk2 atk cairo libxml2-python tcsh libnl tcl tk createrepo
sudo yum install -y rpm-build redhat-rpm-config asciidoc hmaccalc perl-ExtUtils-Embed pesign xmlto
sudo yum install -y audit-libs-devel binutils-devel elfutils-devel elfutils-libelf-devel bc
sudo yum install -y ncurses-devel newt-devel numactl-devel pciutils-devel python-devel zlib-devel

# Get kernel source
rpm -i http://vault.centos.org/$OS_VERSION/updates/Source/SPackages/kernel-"$KERNEL_VERSION".src.rpm 2>&1 | grep -v exist
cd ~/rpmbuild/SPECS
rpmbuild -bp --target=$(uname -m) kernel.spec

# Get kernel config
git clone https://github.com/shashankgugnani/chameleon.git
cp chameleon/config ~/rpmbuild/BUILD/kernel-"$KERNEL_VERSION"/linux-"$KERNEL_VERSION".x86_64/.config
rm -rf chameleon

# Compile the kernel
cd ~/rpmbuild/BUILD/kernel-"$KERNEL_VERSION"/linux-"$KERNEL_VERSION".x86_64/
sudo make olddefconfig
sudo make && sudo make modules && sudo make modules_install
cd ~
